language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_PACKAGE=Django==1.5.1
  - DJANGO_PACKAGE=https://github.com/django/django/archive/master.zip
matrix:
  include:
    - python: "2.6"
      env: DJANGO_PACKAGE=Django==1.4.5
    - python: "2.7"
      env: DJANGO_PACKAGE=Django==1.4.5
install:
  - pip install -q $DJANGO_PACKAGE --use-mirrors
  - python setup.py install
script: make test
